// Minimal ZIP/OOXML adapter. No external requests or dependencies.
const u16=(d,p)=>d[p]|(d[p+1]<<8),u32=(d,p)=>(d[p]|(d[p+1]<<8)|(d[p+2]<<16)|(d[p+3]<<24))>>>0;
const write16=n=>[n&255,(n>>>8)&255],write32=n=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
function crc32(bytes){let c=-1;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^-1)>>>0}
async function transformZip(data,type){const files=[];let tail=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i--)if(u32(data,i)===0x06054b50){tail=i;break}
if(tail<0)throw Error('Archive Office ZIP invalide');const count=u16(data,tail+10),central=u32(data,tail+16);let p=central,parts=[],virtual='',cursor=0;
for(let i=0;i<count;i++){if(u32(data,p)!==0x02014b50)throw Error('Annuaire ZIP invalide');const flag=u16(data,p+8),method=u16(data,p+10),compressed=u32(data,p+20),nameLen=u16(data,p+28),extraLen=u16(data,p+30),commentLen=u16(data,p+32),local=u32(data,p+42),name=new TextDecoder().decode(data.subarray(p+46,p+46+nameLen));if(flag&1)throw Error('Document chiffré non pris en charge');if(method!==0&&method!==8)throw Error('Compression ZIP non prise en charge');
const lp=local+30+u16(data,local+26)+u16(data,local+28);const raw=data.slice(lp,lp+compressed);
let content=raw;if(method===8){if(!('DecompressionStream' in window))throw Error('Ce navigateur ne prend pas en charge la décompression ZIP');const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw'));content=new Uint8Array(await new Response(stream).arrayBuffer())}
const relevant=type==='DOCX'?/^word\/(?:document|header\d*|footer\d*|footnotes|endnotes|comments)\.xml$/.test(name):/^xl\/(?:sharedStrings|worksheets\/sheet\d+)\.xml$/.test(name);
let xml=null,spans=[];if(relevant){xml=new TextDecoder('utf-8',{fatal:true}).decode(content);const re=type==='DOCX'?/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>/g:/<(?:t|v)(?:\s[^>]*)?>([\s\S]*?)<\/(?:t|v)>/g;let m;while((m=re.exec(xml))){const value=decodeXml(m[1]);if(!value)continue;const start=virtual.length;virtual+=value;const end=virtual.length;spans.push({start,end,xmlStart:m.index+m[0].indexOf(m[1]),xmlEnd:m.index+m[0].indexOf(m[1])+m[1].length,part:name});virtual+='\n'} }
parts.push({name,method,content,raw,xml,spans});p+=46+nameLen+extraLen+commentLen}
if(type==='XLSX'){const data=AnonymiseXlsx.build(parts);return {parts,type,...data}}return {parts,source:virtual,spans:parts.flatMap(x=>x.spans),type}
}
function decodeXml(s){return s.replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&')}
function xmlEscape(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
async function exportOffice(office,zones,mask){const entries=[];for(const part of office.parts){let data=part.content;if(part.xml){if(office.type==='XLSX'&&/^xl\/worksheets\/sheet\d+\.xml$/.test(part.name)){data=new TextEncoder().encode(AnonymiseXlsx.modifyPart(part,office.cells.filter(c=>c.part===part.name),zones,mask))}else if(office.type==='XLSX'){data=part.content}else{let xml=part.xml;const changes=[];for(const span of part.spans){const contained=zones.filter(z=>z.strategy!=='keep'&&z.start<span.end&&z.end>span.start);if(!contained.length)continue;let val=decodeXml(xml.slice(span.xmlStart,span.xmlEnd));for(const z of contained.sort((a,b)=>b.start-a.start)){const lo=Math.max(span.start,z.start)-span.start,hi=Math.min(span.end,z.end)-span.start;const original=val.slice(lo,hi);val=val.slice(0,lo)+mask(original,z.type)+val.slice(hi)}changes.push({start:span.xmlStart,end:span.xmlEnd,value:xmlEscape(val)})}
for(const c of changes.sort((a,b)=>b.start-a.start))xml=xml.slice(0,c.start)+c.value+xml.slice(c.end);data=new TextEncoder().encode(xml)}}
let packed=data,method=0;if(part.method===8){const stream=new Blob([data]).stream().pipeThrough(new CompressionStream('deflate-raw'));packed=new Uint8Array(await new Response(stream).arrayBuffer());method=8}
entries.push({name:part.name,raw:packed,method,crc:crc32(data),size:data.length})}
const chunks=[],directory=[];let offset=0;for(const f of entries){const name=new TextEncoder().encode(f.name);const header=new Uint8Array([80,75,3,4,20,0,0,8,...write16(f.method),0,0,0,0,...write32(f.crc),...write32(f.raw.length),...write32(f.size),...write16(name.length),0,0]);chunks.push(header,name,f.raw);const cen=new Uint8Array([80,75,1,2,20,0,20,0,0,8,...write16(f.method),0,0,0,0,...write32(f.crc),...write32(f.raw.length),...write32(f.size),...write16(name.length),0,0,0,0,0,0,0,0,0,0,0,0,...write32(offset)]);directory.push(cen,name);offset+=header.length+name.length+f.raw.length}
const cdsize=directory.reduce((n,a)=>n+a.length,0);const end=new Uint8Array([80,75,5,6,0,0,0,0,...write16(entries.length),...write16(entries.length),...write32(cdsize),...write32(offset),0,0]);return new Blob([...chunks,...directory,end],{type:'application/octet-stream'})}
